### ISSUE TITLE
ESPHome 2022.8.0 removes min_save_interval from integration

### ISSUE THREAD

**Issue by tmugan** [jesserockz/athom-configs#13]
After upgrading to the latest version of ESPHOme integration in HASS, I get an error now with the supplied YAML for the Athom Smart Plug

'''''''

INFO Reading configuration /config/esphome/dishwasher-plug.yaml...
INFO Detected timezone 'Australia/Sydney'
Failed config

sensor.total_daily_energy: [source /config/esphome/.esphome/packages/43f53298/athom-smart-plug-v2.yaml:94]
  platform: total_daily_energy
  name: Athom Smart Plug V2 Total Daily Energy
  restore: True
  
  `min_save_interval` was removed in 2022.6.0. Please use the `preferences` -> `flash_write_interval` to adjust.
  min_save_interval: 180s
  power_id: power_sensor
  unit_of_measurement: kWh
  accuracy_decimals: 3
  filters: 
    - multiply: 0.001

**Comment by tmugan** [comment]
Seems related to this change?
https://github.com/esphome/esphome/pull/3498

**Comment by jesserockz** [comment]
THis has been updated on https://github.com/athom-tech/athom-configs
