### ISSUE TITLE
How can I tell which smart plug version I have?

### ISSUE THREAD

**Issue by axilleas** [jesserockz/athom-configs#7]
:wave: I see there are two configs for the smart plug:

- https://github.com/jesserockz/athom-configs/blob/main/athom-smart-plug.yaml
- https://github.com/jesserockz/athom-configs/blob/main/athom-smart-plug-v2.yaml

I have [this plug](https://www.aliexpress.com/item/1005002984938182.html):

```
Model: PG01
230v
50Hz 16A
3680W
```

Which config should I use?

Thanks!

**Comment by Drizzt321** [comment]
Athom now have the yaml on each product page https://www.athom.tech/blank-1/esphome-eu-plug, so these config probably can be considered deprecated since we have official ones now for all of their products, even the CCT bulbs (15W ones).

**Comment by jesserockz** [comment]
These configs are not exactly deprecated. I keep this repo up to date, and PR into their actual repo which should be considered the true source https://github.com/athom-tech/athom-configs.

@axilleas The plug you have is https://github.com/athom-tech/athom-configs/blob/main/athom-smart-plug.yaml

**Comment by Drizzt321** [comment]
@jesserockz Ah, gotcha. But yes, I'd consider their repo the definitive version as well.

**Comment by axilleas** [comment]
Thanks! Their repo doesn't have issues enabled, so I followed the trail back to this repo and opened an issue in the hope someone would answer me 😄
